tuple12 = ('Crush', 'I love you', 'Like Coding', 'crush', 'Crush')
tuple1 = ('Hehe', 2, False, True, 3j+3, 'Love you now')
tuple2 = (2, 3, 4, 67)
tuple3 = (False, True)
print(tuple12)
print(tuple1)
print(tuple2)
print(tuple3)
single_tuple = ('Python')
single_tuple1 = ('Python', )
print(type(single_tuple))
print(type(single_tuple1))

print('---***---')
tuple4 = tuple(('Django', 'Love Java'))
print(tuple4)
print(type(tuple4))

# print(tuple[0])
# print(tuple[1])
# print(tuple)
# print(len(tuple))
# type 
# index (n-1)